void PrintMatrix(int(*pt)[2]);
void PrintMatrix(int(*pt)[2], int row, int col);
void FillIn(int *p, int row, int col);
void FillIn(int *p, int col);
void PrintMatrix(int *p, int col);
void PrintMatrix(int *p, int row, int col);
int RandomNumber(int *p, int row, int col);
char * ConsistOf(char *p, char *pt);
int Min(int *p, int row, int col);
int Sum(int *pt, int end);
int *Max(int *p, int col);
void swap(int *a, int j);
void sortArray(int*a, int col);
int *findCouples(int *a);
void word(char *arr);
int compare(char *start, char *end, int count);